apiVersion: v1
kind: ConfigMap
metadata:
  name: basket-cm
  labels:
    app: eshop
    service: basket
data:
  ASPNETCORE_ENVIRONMENT: Development
  AzureServiceBusEnabled: "False"
  ConnectionString: eshop-redis-20220218055747309.redis.cache.windows.net:6380,password=vOVSxFomxBw7gcKpUfH7K9O5Ot9fE1vCcAzCaJ4ofrs=,ssl=True,abortConnect=False
  EventBusConnection: rabbitmq
  identityUrl: http://identity-api
  IdentityUrlExternal: {{ .Values.protocol }}://{{ .Values.host }}/identity
  OrchestratorType: K8S
  PATH_BASE: /basket-api
